print("Welcome to the tip calculator!")
bill = float(input("Whats was the total bill ? $"))
tip = int(input("How much tip % would you like to give? 10, 12 or 15?"))
people = int(input("How many people to split the bill? "))
total = ((bill + (bill * (tip/100))) / people)
print("Each person should pay : $" + str(round(total)))
